version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper'
    hostname: localhost
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka'
    hostname: localhost
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_SOCKET_REQUEST_MAX_BYTES=50000000
      - KAFKA_CFG_MESSAGE_MAX_BYTES=50000000
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=60000000
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local